### ISSUE TITLE
Can I use the vm to create a working disk for a physical raq3

### ISSUE THREAD

**Issue by skruglov2023** [gpdm/cobaltos-patcher#1]
Will this work for me to be able to clone the virtual disk to a physical one and then boot a raq3 off it? I've been unsuccessful in getting any raq2/3 to netboot

**Comment by gpdm** [comment]
Sorry for the late response.

Yes and No.
You can certainly install the VM and clone it to a physical hard drive, then putting that one into a RAQ3.

The catch is: The procedure outline with the cobaltos-patcher removes all Cobalt-specific patches and configurations, i.e. disables the LCD display, removes or changes kernel configurations, etc.

As such, it may be the system boots upon a physical RAQ3, but there's no guarantee for it, and I never tested it.

Even if the RAQ3 would boot, the usability of a real Cobalt would be severely impacted.

I'd recommended to not follow that route, but install through regular netboot method instead.
